from typing import Dict, Any
import os
from datetime import datetime

class NodeGenerator:
    """Generates ROS 2 node code from node configurations."""
    
    TEMPLATE_IMPORTS = """#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, QoSReliabilityPolicy, QoSDurabilityPolicy
from rclpy.qos import QoSHistoryPolicy, QoSLivelinessPolicy
{message_imports}
"""

    TEMPLATE_CLASS = """
class {class_name}(Node):
    \"\"\"
    {class_docstring}
    
    Generated by ROSBuddy on {timestamp}
    \"\"\"
    
    def __init__(self):
        super().__init__('{node_name}'{namespace_arg})
        
        # Configure QoS profiles
{qos_profiles}
        
        # Create publishers/subscribers/services/actions
{node_setup}
        
        # Declare parameters
{parameters}
        
        self.get_logger().info(f'{node_name} node is running')
    
{callbacks}
"""

    def __init__(self):
        self.indent = "        "  # 8 spaces for nested indentation
    
    def generate_node(self, config: Dict[str, Any]) -> str:
        """Generate a ROS 2 node class from configuration."""
        # Extract basic info
        node_type = config["type"]
        node_name = config["name"]
        namespace = config.get("namespace", "")
        msg_type = config["msg_type"]
        topic = config["topic"]
        
        # Generate code sections
        imports = self._generate_imports(msg_type, node_type)
        class_name = self._generate_class_name(node_name)
        docstring = self._generate_docstring(node_type, topic, msg_type)
        qos_profiles = self._generate_qos_profiles(config.get("qos", {}))
        node_setup = self._generate_node_setup(node_type, topic, msg_type)
        parameters = self._generate_parameters(config.get("parameters", {}))
        callbacks = self._generate_callbacks(node_type, msg_type)
        
        # Format the complete class
        namespace_arg = f', namespace="{namespace}"' if namespace else ""
        
        return self.TEMPLATE_IMPORTS.format(
            message_imports=imports
        ) + self.TEMPLATE_CLASS.format(
            class_name=class_name,
            class_docstring=docstring,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            node_name=node_name,
            namespace_arg=namespace_arg,
            qos_profiles=qos_profiles,
            node_setup=node_setup,
            parameters=parameters,
            callbacks=callbacks
        )
    
    def _generate_imports(self, msg_type: str, node_type: str) -> str:
        """Generate required imports."""
        imports = []
        
        # Get message package and type
        pkg, msg_category, msg_name = msg_type.split("/")
        
        # Add message import
        imports.append(f"from {pkg}.{msg_category} import {msg_name}")
        
        # Add service/action specific imports
        if node_type == "Service":
            imports.extend([
                "from rclpy.service import Service",
                "from rclpy.callback_groups import ReentrantCallbackGroup"
            ])
        elif node_type == "Action":
            imports.extend([
                "from rclpy.action import ActionServer, ActionClient",
                "from rclpy.callback_groups import ReentrantCallbackGroup"
            ])
        
        return "\n".join(imports)
    
    def _generate_class_name(self, node_name: str) -> str:
        """Generate a valid Python class name."""
        # Convert to CamelCase and ensure it's a valid identifier
        words = node_name.replace("_", " ").title().split()
        class_name = "".join(words)
        if not class_name[0].isalpha():
            class_name = "Node" + class_name
        return class_name
    
    def _generate_docstring(self, node_type: str, topic: str, msg_type: str) -> str:
        """Generate class docstring."""
        type_desc = {
            "Publisher": "Publishes",
            "Subscriber": "Subscribes to",
            "Service": "Provides service for",
            "Action": "Handles action for"
        }
        
        return f"{type_desc[node_type]} {topic} of type {msg_type}"
    
    def _generate_qos_profiles(self, qos_config: Dict[str, Any]) -> str:
        """Generate QoS profile configuration."""
        if not qos_config:
            return f"{self.indent}# Using default QoS profile"
        
        lines = [f"{self.indent}# Configure QoS profile"]
        lines.append(f"{self.indent}self.qos_profile = QoSProfile(")
        
        # Reliability
        reliability = qos_config.get("reliability", "Reliable")
        lines.append(f"{self.indent}    reliability=QoSReliabilityPolicy.{reliability.upper()},")
        
        # Durability
        durability = qos_config.get("durability", "Volatile")
        lines.append(f"{self.indent}    durability=QoSDurabilityPolicy.{durability.upper()},")
        
        # History
        history = qos_config.get("history", {})
        history_kind = history.get("kind", "Keep Last")
        history_depth = history.get("depth", 10)
        lines.append(f"{self.indent}    history=QoSHistoryPolicy.{history_kind.upper().replace(' ', '_')},")
        if history_kind == "Keep Last":
            lines.append(f"{self.indent}    depth={history_depth},")
        
        # Deadline
        deadline = qos_config.get("deadline", 0.0)
        if deadline > 0.0:
            lines.append(f"{self.indent}    deadline=rclpy.duration.Duration(seconds={deadline}),")
        
        # Liveliness
        liveliness = qos_config.get("liveliness", {})
        liveliness_kind = liveliness.get("kind", "Automatic")
        lease_duration = liveliness.get("lease_duration", 0.0)
        lines.append(f"{self.indent}    liveliness=QoSLivelinessPolicy.{liveliness_kind.upper().replace(' ', '_')},")
        if lease_duration > 0.0:
            lines.append(f"{self.indent}    lease_duration=rclpy.duration.Duration(seconds={lease_duration}),")
        
        lines.append(f"{self.indent})")
        
        return "\n".join(lines)
    
    def _generate_node_setup(self, node_type: str, topic: str, msg_type: str) -> str:
        """Generate node setup code (publishers, subscribers, etc.)."""
        pkg, msg_category, msg_name = msg_type.split("/")
        lines = []
        
        if node_type == "Publisher":
            lines.extend([
                f"{self.indent}# Create publisher",
                f"{self.indent}self.publisher = self.create_publisher(",
                f"{self.indent}    {msg_name},",
                f"{self.indent}    '{topic}',",
                f"{self.indent}    self.qos_profile",
                f"{self.indent})"
            ])
        
        elif node_type == "Subscriber":
            lines.extend([
                f"{self.indent}# Create subscription",
                f"{self.indent}self.subscription = self.create_subscription(",
                f"{self.indent}    {msg_name},",
                f"{self.indent}    '{topic}',",
                f"{self.indent}    self.listener_callback,",
                f"{self.indent}    self.qos_profile",
                f"{self.indent})"
            ])
        
        elif node_type == "Service":
            lines.extend([
                f"{self.indent}# Create service",
                f"{self.indent}self.cb_group = ReentrantCallbackGroup()",
                f"{self.indent}self.service = self.create_service(",
                f"{self.indent}    {msg_name},",
                f"{self.indent}    '{topic}',",
                f"{self.indent}    self.service_callback,",
                f"{self.indent}    callback_group=self.cb_group",
                f"{self.indent})"
            ])
        
        elif node_type == "Action":
            lines.extend([
                f"{self.indent}# Create action server",
                f"{self.indent}self.cb_group = ReentrantCallbackGroup()",
                f"{self.indent}self._action_server = ActionServer(",
                f"{self.indent}    self,",
                f"{self.indent}    {msg_name},",
                f"{self.indent}    '{topic}',",
                f"{self.indent}    self.execute_callback,",
                f"{self.indent}    callback_group=self.cb_group",
                f"{self.indent})"
            ])
        
        return "\n".join(lines)
    
    def _generate_parameters(self, parameters: Dict[str, Any]) -> str:
        """Generate parameter declarations."""
        if not parameters:
            return f"{self.indent}# No parameters defined"
        
        lines = [f"{self.indent}# Declare parameters"]
        
        for name, config in parameters.items():
            param_type = config["type"]
            value = config["value"]
            
            if param_type == "string":
                value_str = f"'{value}'"
            elif param_type == "bool":
                value_str = str(value).lower()
            else:
                value_str = str(value)
            
            lines.append(
                f"{self.indent}self.declare_parameter('{name}', {value_str})"
            )
        
        return "\n".join(lines)
    
    def _generate_callbacks(self, node_type: str, msg_type: str) -> str:
        """Generate callback methods."""
        pkg, msg_category, msg_name = msg_type.split("/")
        lines = []
        
        if node_type == "Subscriber":
            lines.extend([
                f"{self.indent}def listener_callback(self, msg: {msg_name}):",
                f"{self.indent}    \"\"\"Handle incoming messages.\"\"\"",
                f"{self.indent}    # TODO: Implement message handling",
                f"{self.indent}    self.get_logger().info(f'Received: {{msg}}')"
            ])
        
        elif node_type == "Service":
            lines.extend([
                f"{self.indent}def service_callback(self, request, response):",
                f"{self.indent}    \"\"\"Handle service requests.\"\"\"",
                f"{self.indent}    # TODO: Implement service logic",
                f"{self.indent}    self.get_logger().info(f'Request: {{request}}')",
                f"{self.indent}    return response"
            ])
        
        elif node_type == "Action":
            lines.extend([
                f"{self.indent}async def execute_callback(self, goal_handle):",
                f"{self.indent}    \"\"\"Handle action goals.\"\"\"",
                f"{self.indent}    # TODO: Implement action execution",
                f"{self.indent}    self.get_logger().info(f'Executing goal: {{goal_handle.request}}')",
                f"{self.indent}    ",
                f"{self.indent}    feedback_msg = {msg_name}.Feedback()",
                f"{self.indent}    result = {msg_name}.Result()",
                f"{self.indent}    ",
                f"{self.indent}    goal_handle.succeed(result)",
                f"{self.indent}    return result"
            ])
        
        return "\n".join(lines) 