from typing import Dict, Any, List
import os
from datetime import datetime

class PackageGenerator:
    """Generates ROS 2 package structure and configuration files."""
    
    TEMPLATE_SETUP_PY = """from setuptools import setup
import os
from glob import glob

package_name = '{package_name}'

setup(
    name=package_name,
    version='0.0.1',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
         ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.py'))
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='{maintainer}',
    maintainer_email='{maintainer_email}',
    description='{description}',
    license='{license}',
    tests_require=['pytest'],
    entry_points={{
        'console_scripts': [
{entry_points}
        ],
    }},
)
"""

    TEMPLATE_PACKAGE_XML = """<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>{package_name}</name>
  <version>0.0.1</version>
  <description>{description}</description>
  <maintainer email="{maintainer_email}">{maintainer}</maintainer>
  <license>{license}</license>

  <depend>rclpy</depend>
{dependencies}

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
"""

    TEMPLATE_LAUNCH = """from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
{node_launches}
    ])
"""

    def __init__(self):
        self.indent = "        "  # 8 spaces for nested indentation
    
    def generate_package(self, package_name: str, nodes: List[Dict[str, Any]], 
                        maintainer: str = "ROSBuddy", 
                        maintainer_email: str = "user@rosbuddy.org",
                        description: str = "Package generated by ROSBuddy",
                        license: str = "Apache-2.0") -> Dict[str, str]:
        """Generate ROS 2 package files."""
        # Collect all message dependencies
        dependencies = set()
        for node in nodes:
            msg_type = node["msg_type"]
            pkg = msg_type.split("/")[0]
            dependencies.add(pkg)
        
        # Generate package files
        files = {
            "setup.py": self._generate_setup_py(
                package_name, nodes, maintainer, maintainer_email, 
                description, license
            ),
            "package.xml": self._generate_package_xml(
                package_name, list(dependencies), maintainer, 
                maintainer_email, description, license
            ),
            f"resource/{package_name}": "",  # Empty marker file
            "launch/nodes.launch.py": self._generate_launch_file(package_name, nodes)
        }
        
        return files
    
    def _generate_setup_py(self, package_name: str, nodes: List[Dict[str, Any]], 
                          maintainer: str, maintainer_email: str,
                          description: str, license: str) -> str:
        """Generate setup.py content."""
        # Generate entry points for each node
        entry_points = []
        for node in nodes:
            node_name = node["name"]
            class_name = self._to_class_name(node_name)
            entry_points.append(
                f'{self.indent}    "{node_name} = {package_name}.{node_name}:{class_name}.main",'
            )
        
        return self.TEMPLATE_SETUP_PY.format(
            package_name=package_name,
            maintainer=maintainer,
            maintainer_email=maintainer_email,
            description=description,
            license=license,
            entry_points="\n".join(entry_points)
        )
    
    def _generate_package_xml(self, package_name: str, dependencies: List[str],
                            maintainer: str, maintainer_email: str,
                            description: str, license: str) -> str:
        """Generate package.xml content."""
        # Generate dependency tags
        dep_tags = []
        for dep in sorted(dependencies):
            dep_tags.append(f"  <depend>{dep}</depend>")
        
        return self.TEMPLATE_PACKAGE_XML.format(
            package_name=package_name,
            maintainer=maintainer,
            maintainer_email=maintainer_email,
            description=description,
            license=license,
            dependencies="\n".join(dep_tags)
        )
    
    def _generate_launch_file(self, package_name: str, nodes: List[Dict[str, Any]]) -> str:
        """Generate launch file content."""
        # Generate node launches
        launches = []
        for node in nodes:
            node_name = node["name"]
            namespace = node.get("namespace", "")
            
            launch_params = [
                f"{self.indent}    Node(",
                f"{self.indent}        package='{package_name}',",
                f"{self.indent}        executable='{node_name}',",
                f"{self.indent}        name='{node_name}',"
            ]
            
            if namespace:
                launch_params.append(
                    f"{self.indent}        namespace='{namespace}',"
                )
            
            # Add parameters if any
            if node.get("parameters"):
                params = []
                for name, config in node["parameters"].items():
                    value = config["value"]
                    if config["type"] == "string":
                        value = f"'{value}'"
                    elif config["type"] == "bool":
                        value = str(value).lower()
                    params.append(f"            '{name}': {value}")
                
                if params:
                    launch_params.extend([
                        f"{self.indent}        parameters=[{{",
                        ",\n".join(params),
                        f"{self.indent}        }}],"
                    ])
            
            launch_params.append(f"{self.indent}    ),")
            launches.append("\n".join(launch_params))
        
        return self.TEMPLATE_LAUNCH.format(
            node_launches="\n\n".join(launches)
        )
    
    def _to_class_name(self, node_name: str) -> str:
        """Convert node name to class name."""
        words = node_name.replace("_", " ").title().split()
        class_name = "".join(words)
        if not class_name[0].isalpha():
            class_name = "Node" + class_name
        return class_name 