<?xml version="1.0"?>
<package format="3">
  <name>my_detailed_py_pkg_for_cmake_test</name>
  <version>2.1.1</version>
  <description>A Python package alongside CMake test.</description>
  <maintainer email="main.dev@example.com">Main Developer</maintainer>
  <license>Apache License 2.0</license>
  <depend>std_msgs</depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <build_type>ament_python</build_type>
<test_depend>ament_copyright</test_depend>
<test_depend>ament_flake8</test_depend>
<test_depend>ament_pep257</test_depend>
<test_depend>python3-pytest</test_depend>
</package>