<?xml version="1.0"?>
<package format="3">
  <name>my_detailed_py_pkg</name>
  <version>2.1.0</version>
  <description>A more detailed Python package for testing XML generation.</description>
  <maintainer email="main.dev@example.com">Main Developer</maintainer>
  <maintainer email="second.dev@example.com">Secondary Dev</maintainer>
  <license>Apache License 2.0</license>
  <license>BSD-3-Clause</license>
  <author email="dr.robot@example.com">Dr. Robot</author>
  <author>Robo Helper</author>
  <url type="website">http://myrobot.example.com/wiki</url>
  <url type="bugtracker">http://myrobot.example.com/issues</url>
  <url type="repository">https://github.com/myrobot/my_detailed_py_pkg</url>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <test_depend>ament_lint_common</test_depend>
  <exec_depend version_gte="5.1">python3-yaml</exec_depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <build_type>ament_python</build_type>
  <architecture_independent/>
  <gazebo_ros plugin_path="${prefix}/lib"/>
<test_depend>ament_copyright</test_depend>
<test_depend>ament_flake8</test_depend>
<test_depend>ament_pep257</test_depend>
<test_depend>python3-pytest</test_depend>
</package>