<?xml version="1.0"?>
<package format="3">
  <name>my_adv_cmake_pkg</name>
  <version>1.0.0</version>
  <description>Advanced CMake package with targets, launch, and config.</description>
  <maintainer email="cmaker@example.com">CMake Pro</maintainer>
  <license>MIT</license>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_type>ament_cmake</build_type>
<test_depend>ament_copyright</test_depend>
<test_depend>ament_flake8</test_depend>
<test_depend>ament_pep257</test_depend>
<test_depend>python3-pytest</test_depend>
</package>