<?xml version="1.0"?>
<package format="3">
  <name>cmake_pkg_with_interfaces</name>
  <version>1.0.0</version>
  <description>CMake package to test interface definitions.</description>
  <maintainer email="if_cmake@example.com">CMake Interface Dev</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <depend>std_msgs</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

<export>
  <build_type>ament_cmake</build_type>
  <member_of_group>rosidl_interface_packages</member_of_group>
  </export>

<test_depend>ament_copyright</test_depend>
<test_depend>ament_flake8</test_depend>
<test_depend>ament_pep257</test_depend>
<test_depend>python3-pytest</test_depend>
</package>