<?xml version="1.0"?>
<package format="3">
  <name>py_pkg_with_launch</name>
  <version>4.0.0</version>
  <description>Python package to test launch file generation and installation.</description>
  <maintainer email="launcher@example.com">Launch Dev</maintainer>
  <license>Apache License 2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <build_type>ament_python</build_type>
<test_depend>ament_copyright</test_depend>
<test_depend>ament_flake8</test_depend>
<test_depend>ament_pep257</test_depend>
<test_depend>python3-pytest</test_depend>
</package>